accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('myprofile', views.myprofile, name='myprofile'),
    path('dashboard', views.dashboard, name='dashboard'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

resume/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve

urlpatterns = [
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),

    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root':       settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from django.db.models.deletion import DO_NOTHING


    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    full_name = models.CharField(max_length=100)
    father_name = models.CharField(max_length=100)
    mother_name = models.CharField(max_length=100)
    profession = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    main_title = models.CharField(max_length=150)
    dob = models.DateField(null=True, auto_now=False)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)
    website = models.CharField(max_length=100)
    gender_choice = [('M','Male'),('F','Female'),('N','Neutral')]
    gender = models.CharField(max_length=5,choices=gender_choice,default='M')
    religion = models.CharField(max_length=20)
    marriage_choice = [('S','Single'),('M','Married'),('U','Unmarried')]
    marital_state = models.CharField(max_length=5,choices=marriage_choice,default='S')
    is_published = models.BooleanField(default=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.full_name
class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    image_path = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.user)
class HirePlatform(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    platform_title = models.CharField(max_length=100)
    platform_description = models.TextField(blank=True)
    platform_profile_link = models.CharField(max_length=100)
    platform_hire_link = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.platform_title


class Skill(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    skill_name = models.CharField(max_length=100)
    skill_level = models.IntegerField()
    skill_details = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.skill_name


class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    company_name = models.CharField(max_length=100)
    designation = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    responsibility = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.company_name


class Education(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    institute_name = models.CharField(max_length=100)
    degree = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.degree


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return self.category_name


class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    category_id = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    portfolio_title = models.CharField(max_length=100)
    portfolio_desc = models.TextField(blank=True)
    web_link = models.CharField(max_length=100)
    image_path = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.portfolio_title


class Training(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    training_name = models.CharField(max_length=100)
    institute = models.CharField(max_length=100)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.training_name

accounts/views.py
from django.http import request
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from users.models import Profile
from users.models import Skill, Image, HirePlatform, Education, Experience, Category, Portfolio, Training

def register(request):
    if request.method == 'POST':
        #Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        #Check if password match
        if password == password2:
            #check username exists
            if User.objects.filter(username=username).exists():
                messages.error(request, 'That username is taken')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'That email is being used')
                    return redirect('register')
                else:
                    user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, password=password, email=email, is_staff=True)
                    profile = Profile.objects.create(user=User.objects.latest('id'), full_name = first_name +' '+ last_name, email=email)
                    #Login after register
                    # auth.login(request, user)
                    # messages.success(request, 'You are now logged In')
                    # return redirect('index')
                    group = Group.objects.get(name='General')
                    user.groups.add(group)
                    #user.is_staff=True
                    user.save()
                    profile.save()
                    messages.success(request, 'You are now registered and can Log In')
                    return redirect('login')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('register')
    else:
        return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('/admin')
        else:
            messages.error(request, 'Invalid username or password')
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, 'You are now logged out')
        return redirect('login')

def myprofile(request):
    user_auth_id = request.user.id
    #user_auth_id = 3
    auth_users = User.objects.filter(id=request.user.id)
    profiles = Profile.objects.filter(is_published=True, user=user_auth_id)
    images = Image.objects.filter(is_active=True, user=user_auth_id)
    hireplatforms = HirePlatform.objects.filter(is_active=True, user=user_auth_id)
    skills = Skill.objects.filter(is_active=True, user=user_auth_id)
    educations = Education.objects.filter(is_active=True, user=user_auth_id)
    experiences = Experience.objects.filter(is_active=True, user=user_auth_id)
    categories = Category.objects.filter(user=user_auth_id)
    portfolios = Portfolio.objects.filter(is_active=True, user=user_auth_id)
    trainings = Training.objects.filter(is_active=True, user=user_auth_id)


    context = {
        'auth_users': auth_users,
        'users': profiles,
        'images': images,
        'hireplatforms': hireplatforms,
        'skills': skills,
        'educations': educations,
        'experiences': experiences,
        'categories': categories,
        'portfolios': portfolios,
        'trainings': trainings
    }

    return render(request, 'accounts/myprofile.html', context)

def dashboard(request):
    # user_auth_id = request.user.id
    # #user_auth_id = 3
    # auth_users = User.objects.filter(id=request.user.id)
    # profiles = Profile.objects.filter(is_published=True, user=user_auth_id)
    


    # context = {
    #     'auth_users': auth_users,
    #     'users': profiles,
    # }

    return redirect('/admin')

templates/accounts/dashboard.html
{% load static %} {% load humanize %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Custom Theme files -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/nav_sidebar.css' %}">
    <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}">

    <!-- Custom Theme files -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Sk. Abu Shahed Alam's Resume" />
    <!-- webfonts -->
    <link href="//fonts.googleapis.com/css?family=Asap:400,700,400italic" rel="stylesheet" type="text/css" />
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- webfonts -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
    <script type="text/javascript">
      jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
          event.preventDefault();
          $("html,body").animate(
            { scrollTop: $(this.hash).offset().top },
            1000
          );
        });
      });
    </script>
    <!-- start-smoth-scrolling -->
    <title>Resume {% block title %} | Dashboard {% endblock %} </title>
  </head>

  <body>
    <!-- Top Bar -->
    {% include 'partials/_topbar.html' %}


    <!-- Container -->
    <div id="container">

    <div class="breadcrumbs">
        <a href="/admin/">Home</a>
        &rsaquo; <a href="/admin/users/">Users</a>
        &rsaquo; <a href="/admin/users/education/">Educations</a>
        &rsaquo; Add education
    </div>
        <div class="main shifted" id="main">
        
    <button class="sticky toggle-nav-sidebar" id="toggle-nav-sidebar" aria-label="Toggle navigation"></button>
    <nav class="sticky" id="nav-sidebar">
    
        <div class="app-auth module">
        <table>
            <caption>
            Profile Information Update
            </caption>
            <tr class="model-group">
              <th scope="row"><a href="/accounts/dashboard">Profile</a></th>
                <td><a href="/accounts/dashboard" class="changelink">Update</a></td>
            </tr>
        </table>
        </div>
    
        <div class="app-users module current-app">
        <table>
            <caption>
            <a href="/admin/users/" class="section" title="Models in the Users application">Personalize Information</a>
            </caption>
            
            <tr class="model-category">
                
                <th scope="row"><a href="/admin/users/category/">Categorys</a></th>
                <td><a href="/admin/users/category/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-education current-model">
                
                <th scope="row"><a href="/admin/users/education/" aria-current="page">Educations</a></th>
                <td><a href="/admin/users/education/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-experience">
                
                <th scope="row"><a href="/admin/users/experience/">Experiences</a></th>
                <td><a href="/admin/users/experience/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-hireplatform">
                
                <th scope="row"><a href="/admin/users/hireplatform/">Hire platforms</a></th>
                <td><a href="/admin/users/hireplatform/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-image">
                
                <th scope="row"><a href="/admin/users/image/">Images</a></th>
                <td><a href="/admin/users/image/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-portfolio">
                
                <th scope="row"><a href="/admin/users/portfolio/">Portfolios</a></th>
                <td><a href="/admin/users/portfolio/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-profile">
                
                <th scope="row"><a href="/admin/users/profile/">Profiles</a></th>
                <td><a href="/admin/users/profile/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-skill">
                
                <th scope="row"><a href="/admin/users/skill/">Skills</a></th>
                <td><a href="/admin/users/skill/add/" class="addlink">Add</a></td>
            </tr>
            
            <tr class="model-training">
                
                <th scope="row"><a href="/admin/users/training/">Trainings</a></th>
                <td><a href="/admin/users/training/add/" class="addlink">Add</a></td>
            </tr>
            
        </table>
        </div>
    </nav>

        <div class="content">
            <!-- Content -->
            <div id="content" class="colM">
            <!-- Alerts -->
            {% include 'partials/_alerts.html' %}

            <h1>Add education</h1>
            
            <div id="content-main">
    <form method="post" id="education_form" novalidate><input type="hidden" name="csrfmiddlewaretoken" value="J40ESruP59TsK0xWaSQQJUnA4IqnDK0NTkuZQSqmBuJckEL0x7ei7lJJI0gCvuHo">
    <div>
    <fieldset class="module aligned ">
            
        
            <div class="form-row field-institute_name">
                    <div>
                            <label class="required" for="id_institute_name">Institute name:</label>
                            
                                <input type="text" name="institute_name" class="vTextField" maxlength="100" required id="id_institute_name">
                            
                    </div>
                
            </div>
        
            <div class="form-row field-degree">
                    <div>
                            <label class="required" for="id_degree">Degree:</label>
                            
                                <input type="text" name="degree" class="vTextField" maxlength="50" required id="id_degree">
                            
                    </div>
                
            </div>
        
            <div class="form-row field-location">
                    <div>
                            <label class="required" for="id_location">Location:</label>
                            
                                <input type="text" name="location" class="vTextField" maxlength="100" required id="id_location">
                    
                    </div>
                
            </div>
        
            <div class="form-row field-start_date">
                    <div>
                            <label class="required" for="id_start_date">Start date:</label>
                            
                                <input type="text" name="start_date" class="vDateField" size="10" required id="id_start_date">
                            
                    </div>
                
            </div>
        
            <div class="form-row field-end_date">
                    <div>
                            <label class="required" for="id_end_date">End date:</label>
                            
                                <input type="text" name="end_date" class="vDateField" size="10" required id="id_end_date">
                            
                    </div>
                
            </div>
        
            <div class="form-row field-description">
                    <div>
                            <label for="id_description">Description:</label>
                            
                                <textarea name="description" cols="40" rows="10" class="vLargeTextField" id="id_description">
    </textarea>     
                    </div>
                
            </div>
        
            <div class="form-row field-is_active">
                    <div class="checkbox-row">
                            <input type="checkbox" name="is_active" id="id_is_active" checked><label class="vCheckboxLabel" for="id_is_active">Is active</label>
                        
                    </div>
                
            </div>
        
    </fieldset>
    <div class="submit-row">

    <input type="submit" value="Save" class="default" name="_save">


    <input type="submit" value="Save and add another" name="_addanother">
    <input type="submit" value="Save and continue editing" name="_continue">


    </div>
        <script id="django-admin-form-add-constants"
                src="/static/admin/js/change_form.js"
                
                    data-model-name="education"
                
                async>
        </script>
    <script id="django-admin-prepopulated-fields-constants"
            src="/static/admin/js/prepopulate_init.js"
            data-prepopulated-fields="[]">
    </script>


    </div>
    </form></div>
            <br class="clear">
            </div>
            <!-- END Content -->
            <div id="footer"></div>
        </div>
        </div>
    </div>
    <!-- END Container -->

    <a href="#home" id="toTop" style="display: block">
      <span id="toTopHover" style="opacity: 1"> </span>
    </a>
    <!--start-smooth-scrolling-->
    <script type="text/javascript">
      $(document).ready(function () {
        $().UItoTop({ easingType: "easeOutQuart" });
      });
    </script>
    <!--end-smooth-scrolling-->
    <!-- //for bootstrap working -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} | Account Login
{% endblock %}

{% block content %}

<div class="body-form">
  <form action={% url 'login' %} id="login-form" method="POST">
   {% csrf_token %}
      <div class="con">
      <!--     Start  header Content  -->
         <header class="head-form">
            <h2>Log In</h2>
            <p>Login here using your username and password</p>
         </header>
         <!--     End  header Content  -->

         <!-- Alerts -->
         {% include 'partials/_alerts.html' %}

         <div class="field-set">
               <span class="input-item">
               <i class="fa fa-user-circle"></i>
               </span>
               <input class="form-input" id="txt-input" name="username" type="text" placeholder="Enter UserName" required>
            <br>
            <span class="input-item">
            <i class="fa fa-key"></i>
            </span>
            <input class="form-input" type="password" placeholder="Enter Password" id="pwd"  name="password" required>
         <span>
            <i class="fa fa-eye eye" aria-hidden="true"  type="button" id="eye"></i>
         </span>
            <br>
            <button class="log-in" type="submit"> Log In </button>
         </div>
      
         <div class="other">
            <button class="btn submits frgt-pass"><a href="{% url 'password_reset' %}" >Forgot Password</a></button>
            <button class="btn submits sign-up"><a href="{% url 'register' %}" >Sign Up</a>
            <i class="fa fa-user-plus" aria-hidden="true"></i>
            </button>
         </div>
      </div>
   </form>
</div>
{% endblock %}

templates/accounts/myprofile.html
{% extends 'base.html' %}

{% block title %} | User Profile
{% endblock %}

{% block content %}

<!-- Alerts -->
{% include 'partials/_alerts.html' %}

<!-- Top Bar -->
{% include 'partials/_navbar.html' %}

<!-- About Section -->
{% include 'partials/_about.html' %}

<!-- Service Section -->
{% include 'partials/_service.html' %}

<!-- Experience Section -->
{% include 'partials/_experience.html' %}

<!-- Education Section -->
{% include 'partials/_education.html' %}

<!-- Portfolio Section -->
{% include 'partials/_portfolio.html' %}

<!-- Training Section -->
{% include 'partials/_training.html' %}

<!-- Footer -->
{% include 'partials/_footer.html' %}

{% endblock %}

templates/accounts/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

templates/accounts/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'login' %}">Log in</a>

templates/accounts/password_reset_form.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>

templates/accounts/password_reset_sent.html
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} | Sign Up | Register
{% endblock %}

{% block content %}

<div class="body-form">
   <form action={% url 'register' %} id="login-form" method="POST">
    {% csrf_token %}
      <div class="con">
      <!--     Start  header Content  -->
         <header class="head-form">
            <h2>Sign Up</h2>
            <p>Please enter sign up details</p>
         </header>
         <!--     End  header Content  -->
         
         <!-- Alerts -->
         {% include 'partials/_alerts.html' %}

         <div class="field-set">
            <span class="input-item">
               <i class="fa fa-user-alt"></i>
            </span>
            <input class="form-input" id="txt-input" type="text" name="first_name" placeholder="Enter First Name" required>
            <br>

            <span class="input-item">
               <i class="fa fa-user-circle"></i>
            </span>
            <input class="form-input" id="txt-input" type="text" name="last_name" placeholder="Enter Last Name" required>
            <br>

            <span class="input-item">
               <i class="fa fa-envelope-open"></i>
            </span>
            <input class="form-input" id="txt-input" type="Email" name="email" placeholder="Enter Email" required>
            <br>

            <span class="input-item">
               <i class="fa fa-smile"></i>
            </span>
            <input class="form-input" id="txt-input" type="text" name="username" placeholder="Enter UserName" required>
            <br>

            <span class="input-item">
                <i class="fa fa-key"></i>
            </span>
            <input class="form-input" type="password" placeholder="Enter Password" id="pwd"  name="password" required>

            <span>
                <i class="fa fa-eye eye" aria-hidden="true"  type="button" id="eye"></i>
            </span>
            <br>

            <span class="input-item">
                <i class="fa fa-repeat"></i>
            </span>
            <input class="form-input" type="password" placeholder="Confirm Password" id="pwd2"  name="password2" required>

            <span>
                <i class="fa fa-eye eye" aria-hidden="true"  type="button" id="eye2"></i>
            </span>
            <br>

            <button class="log-in"> Sign Up <i class="fa fa-user-plus" aria-hidden="true"></i></button>
         </div>
      
         <div class="other">
            <span > Already a member? <button id="login-btn" ><a href="{% url 'login' %}" >Log In</a></button></span>
         </div>
      </div>
   </form>
</div>
{% endblock %}